function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t393_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t393").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("visibility","visible");el.animate({"opacity":"1"},300,function(){})}}else{el.stop();el.css("visibility","hidden")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(el.css('visibility')!='hidden'){el.finish();el.css("visibility","hidden")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.css("visibility","visible")}}else{el.stop();el.css("visibility","visible")}}}})}}
function t450_showMenu(recid){var el=$('#rec'+recid);$('body').addClass('t450__body_menushowed');el.find('.t450').addClass('t450__menu_show');el.find('.t450__overlay').addClass('t450__menu_show');$('.t450').bind('clickedAnchorInTooltipMenu',function(){t450_closeMenu()});el.find('.t450__overlay, .t450__close, a[href*=#]').click(function(){var url=$(this).attr('href');if(typeof url!='undefined'&&url!=''&&(url.substring(0,7)=='#price:'||url.substring(0,9)=='#submenu:')){return}
t450_closeMenu()});$(document).keydown(function(e){if(e.keyCode==27){$('body').removeClass('t390__body_popupshowed');$('.t390').removeClass('t390__popup_show')}})}
function t450_closeMenu(){$('body').removeClass('t450__body_menushowed');$('.t450').removeClass('t450__menu_show');$('.t450__overlay').removeClass('t450__menu_show')}
function t450_checkSize(recid){var el=$('#rec'+recid).find('.t450');var windowheight=$(window).height()-80;var contentheight=el.find(".t450__top").height()+el.find(".t450__rightside").height();if(contentheight>windowheight){el.addClass('t450__overflowed');el.find(".t450__container").css('height','auto')}}
function t450_appearMenu(recid){var el=$('#rec'+recid);var burger=el.find(".t450__burger_container");burger.each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");var hideoffset=el.attr("data-hideoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t450__beforeready')){el.finish();el.removeClass("t450__beforeready")}}else{el.stop();el.addClass("t450__beforeready")}}
if(hideoffset!=""){if(hideoffset.indexOf('vh')>-1){hideoffset=Math.floor((window.innerHeight*(parseInt(hideoffset)/100)))}
hideoffset=parseInt(hideoffset,10);if($(window).scrollTop()+$(window).height()>=$(document).height()-hideoffset){if(!el.hasClass('t450__beforeready')){el.finish();el.addClass("t450__beforeready")}}else{if(appearoffset!=""){if($(window).scrollTop()>=appearoffset){el.stop();el.removeClass("t450__beforeready")}}else{el.stop();el.removeClass("t450__beforeready")}}}})}
function t450_initMenu(recid){var el=$('#rec'+recid).find('.t450');var hook=el.attr('data-tooltip-hook');if(hook!==''){var obj=$('a[href="'+hook+'"]');obj.click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid);e.preventDefault()})}
$('#rec'+recid).find('.t450__burger_container').click(function(e){t450_closeMenu();t450_showMenu(recid);t450_checkSize(recid)});if(isMobile){$('#rec'+recid).find('.t-menu__link-item').each(function(){var $this=$(this);if($this.hasClass('t450__link-item_submenu')){$this.on('click',function(){setTimeout(function(){t450_checkSize(recid)},100)})}})}
t450_highlight()}
function t450_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t450__menu a[href='"+url+"']").addClass("t-active");$(".t450__menu a[href='"+url+"/']").addClass("t-active");$(".t450__menu a[href='"+pathname+"']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"']").addClass("t-active");$(".t450__menu a[href='"+pathname+"/']").addClass("t-active");$(".t450__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t698_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t698_onSuccess(t698_form){var t698_inputsWrapper=t698_form.find('.t-form__inputsbox');var t698_inputsHeight=t698_inputsWrapper.height();var t698_inputsOffset=t698_inputsWrapper.offset().top;var t698_inputsBottom=t698_inputsHeight+t698_inputsOffset;var t698_targetOffset=t698_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t698_target=t698_targetOffset-200}else{var t698_target=t698_targetOffset-100}
if(t698_targetOffset>$(window).scrollTop()||($(document).height()-t698_inputsBottom)<($(window).height()-100)){t698_inputsWrapper.addClass('t698__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t698_target},400);setTimeout(function(){t698_inputsWrapper.addClass('t698__inputsbox_hidden')},400)}
var successurl=t698_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t708_initPopup(recid){$('#rec'+recid).attr('data-animationappear','off');$('#rec'+recid).css('opacity','1');var el=$('#rec'+recid).find('.t708__popup'),analitics=el.attr('data-track-popup'),hook="TildaSendMessageWidget"+recid,obj=$('#rec'+recid+' .t708__btn');obj.click(function(e){if(obj.hasClass("t708__btn_active")){t708_closePopup();return}
obj.addClass("t708__btn_active");$('#rec'+recid+' .t708').addClass("t708_active");t708_showPopup(recid);e.preventDefault();if(analitics>''){Tilda.sendEventToStatistics(analitics,hook)}})}
function t708_lockScroll(){var body=$("body");if(!body.hasClass('t-body_scroll-locked')){var bodyScrollTop=(typeof window.pageYOffset!=='undefined')?window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;body.addClass('t-body_scroll-locked');console.log("class added");body.css("top","-"+bodyScrollTop+"px");body.attr("data-popup-scrolltop",bodyScrollTop)}}
function t708_unlockScroll(){var body=$("body");if(body.hasClass('t-body_scroll-locked')){var bodyScrollTop=$("body").attr("data-popup-scrolltop");body.removeClass('t-body_scroll-locked');body.css("top","");body.removeAttr("data-popup-scrolltop")
window.scrollTo(0,bodyScrollTop)}}
function t708_showPopup(recid){var el=$('#rec'+recid),popup=el.find('.t708__popup');$('.t708__btn_wrapper').removeClass('t708__btn_animate');$('.t708__btn-text').css('display','none');if($(window).width()<960){$('body').addClass('t708__body_popupshowed')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&$(window).width()<960){console.log("lock scroll");setTimeout(function(){t708_lockScroll()},500)}
popup.css('display','block');el.find('.t-range').trigger('popupOpened');setTimeout(function(){popup.addClass('t708__popup_show')},50);el.find(".t708__mobile-icon-close").click(function(e){t708_closePopup()});$(document).keydown(function(e){if(e.keyCode==27){t708_closePopup()}})}
function t708_closePopup(){if($(window).width()<960){$('body').removeClass('t708__body_popupshowed')}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream){t708_unlockScroll()}
$('.t708').removeClass("t708_active");$('.t708__btn').removeClass('t708__btn_active');$('.t708__popup').removeClass('t708__popup_show');setTimeout(function(){$('.t708__popup').not('.t708__popup_show').css('display','none')},300)}
function t708_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)=='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t708_onSuccess(t708_form){var t708_inputsWrapper=t708_form.find('.t-form__inputsbox');var t708_inputsHeight=t708_inputsWrapper.height();var t708_inputsOffset=t708_inputsWrapper.offset().top;var t708_inputsBottom=t708_inputsHeight+t708_inputsOffset;var t708_targetOffset=t708_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t708_target=t708_targetOffset-200}else{var t708_target=t708_targetOffset-100}
if(t708_targetOffset>$(window).scrollTop()||($(document).height()-t708_inputsBottom)<($(window).height()-100)){t708_inputsWrapper.addClass('t708__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t708_target},400);setTimeout(function(){t708_inputsWrapper.addClass('t708__inputsbox_hidden')},400)}
var successurl=t708_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t911_init(recid){t911_checkPhoneNumber(recid)}
function t911_checkPhoneNumber(recid){var el=$('#rec'+recid);var whatsapp=el.find('.t911__whatsapp').attr('data-messenger-whatsapp');var telegram=el.find('.t911__telegram').attr('data-messenger-telegram');var telegramLink=el.find('.t911__telegram_link').attr('data-messenger-telegram-link');var vk=el.find('.t911__vk').attr('data-messenger-vk');var skype=el.find('.t911__skype').attr('data-messenger-skype');var skypeChat=el.find('.t911__skype_chat').attr('data-messenger-skype-chat');var mail=el.find('.t911__mail').attr('data-messenger-mail');var viber=el.find('.t911__viber').attr('data-messenger-viber');var fb=el.find('.t911__fb').attr('data-messenger-fb');var phone=el.find('.t911__phone').attr('data-messenger-phone');if(typeof telegramLink!='undefined'){if(telegramLink.search(/http/i)!==-1){el.find('.t911__telegram_link').attr('href',telegramLink)}else{if(telegramLink.search(/tg/i)!==-1){el.find('.t911__telegram_link').attr('href',telegramLink)}else{el.find('.t911__telegram_link').attr('href','https://'+telegramLink)}}}
if(typeof whatsapp!='undefined'){el.find('.t911__whatsapp').attr('href','https://api.whatsapp.com/send?phone='+whatsapp.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t911__telegram').attr('href','https://t.me/'+telegram);el.find('.t911__vk').attr('href','https://vk.me/'+vk);if(typeof skype!='undefined'){el.find('.t911__skype').attr('href','skype:'+skype.replace(/[+?^${}()|[\]\\\s]/g,'')+'?call')}
if(typeof skypeChat!='undefined'){el.find('.t911__skype_chat').attr('href','skype:'+skypeChat.replace(/[+?^${}()|[\]\\\s]/g,'')+'?chat')}
if(typeof viber!='undefined'){el.find('.t911__viber').attr('href','viber://chat?number=%2B'+viber.replace(/[+?^${}()|[\]\\\s]/g,''))}
el.find('.t911__mail').attr('href','mailto:'+mail);el.find('.t911__fb').attr('href','https://m.me/'+fb);if(typeof phone!='undefined'){el.find('.t911__phone').attr('href','tel:+'+phone.replace(/[+?^${}()|[\]\\\s]/g,''))}}